apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: servicio-token-sorteo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: servicio-token-sorteo
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
