apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-api-ecocycle-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Ajusta según tus necesidades
