version: '3.9'

services:
  java_api_ecocycle:
    container_name: java_api_ecocycle
    image: dssd-java-api-ecocycle:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8081"
    depends_on:
      - java_api_ecocycle_db
    environment:
      - DB_API_URL=jdbc:postgresql://java_api_ecocycle_db:5432/api_ecocycle
      - DB_API_USERNAME=postgres
      - DB_API_PASSWORD=admin
      - JWT_KEY=333c1f3213beaaa1ca58fsssd2a9ssb4c4333c1f3213beaaa1ca58fsssd2a9ssb4c4
    networks:
      - api_network # Red compartida dentro de Ecocycle
      - app_api_network # Red compartida para comunicación con los otros servicios (Angular, Java, Bonita)

  java_api_ecocycle_db:
    container_name: java_api_ecocycle_db
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api_ecocycle
    networks:
      - api_network # Red compartida dentro de Ecocycle

networks:
  api_network:
  app_api_network: # Red compartida para comunicación con Angular y Java App
    external: true
